# Generated by Django 5.0.6 on 2024-08-07 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0005_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContacUs',
        ),
        migrations.RemoveField(
            model_name='userprofiledetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='UserProfileDetails',
        ),
    ]
