# Generated by Django 5.0.6 on 2024-08-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0008_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOrdersProduct',
        ),
    ]
