# Generated by Django 5.0.6 on 2024-08-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_contactus_created_at_contactus_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='status',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='phonenumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
