# Generated by Django 5.1 on 2024-08-14 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0008_alter_product_average_rating_alter_product_discount'),
        ('profileapp', '0014_wishlist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'product')},
        ),
    ]
