# Generated by Django 5.0.6 on 2024-08-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_alter_order_customer_shippingaddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContacUs',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='country',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='landmark',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
