# Generated by Django 5.0.6 on 2024-08-07 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_delete_contacus_shippingaddress_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
