# Generated by Django 5.0.6 on 2024-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_rename_userprofiledetails_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContacUs',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='order',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='userordersproduct',
            name='user',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='firtsname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='images',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobileno',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
        migrations.DeleteModel(
            name='UserOrdersProduct',
        ),
    ]
