# Generated by Django 5.0.6 on 2024-08-07 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0019_delete_contactus_alter_shippingaddress_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='quantity',
        ),
    ]
