# Generated by Django 5.0.6 on 2024-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0020_remove_orderitems_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
