# Generated by Django 5.0.6 on 2024-08-08 05:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0022_remove_shippingaddress_order_orderitems_shiping'),
        ('profileapp', '0008_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='shiping',
        ),
        migrations.AddField(
            model_name='order',
            name='shiping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileapp.shippingaddress'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
