# Generated by Django 5.0.6 on 2024-08-08 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0023_remove_orderitems_shiping_order_shiping_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='shiping',
            new_name='shipping',
        ),
    ]
