# Generated by Django 5.0.6 on 2024-08-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0024_rename_shiping_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='serching',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
