# Generated by Django 5.0.6 on 2024-08-12 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0027_alter_orderitems_product_order_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='price_at_order',
        ),
    ]
