# Generated by Django 5.1 on 2024-08-13 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0030_paymenthistory'),
        ('profileapp', '0012_remove_shippingaddress_is_primary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profileapp.customer'),
        ),
    ]
