# Generated by Django 5.1 on 2024-08-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0031_paymenthistory_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
