# Generated by Django 5.1 on 2024-08-13 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0032_remove_order_transaction_id_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='trnaxactionid',
            new_name='trnasaction_id',
        ),
    ]
