# Generated by Django 5.1 on 2024-08-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0033_rename_trnaxactionid_paymenthistory_trnasaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='order_ids',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
